-- Create the euroleague_team_stats table if it doesn't exist
CREATE TABLE IF NOT EXISTS euroleague_team_stats (
  season INTEGER,
  phase TEXT,
  position INTEGER,
  teamcode TEXT,
  name TEXT,
  teamlogo TEXT,
  w INTEGER,
  l INTEGER,
  win_percent REAL,
  diff INTEGER,
  home TEXT,
  away TEXT,
  l10 TEXT,
  streak TEXT,
  efg REAL,
  to_percent REAL,
  oreb_percent REAL,
  ftrate REAL,
  efg_opp REAL,
  to_percent_opp REAL,
  oreb_percent_opp REAL,
  ftrate_opp REAL
);

-- Create the euroleague_team_advanced table if it doesn't exist
CREATE TABLE IF NOT EXISTS euroleague_team_advanced (
  name TEXT,
  teamcode TEXT,
  teamlogo TEXT,
  season INTEGER,
  phase TEXT,
  pace REAL,
  pace_opp REAL,
  efficiency REAL,
  efficiency_opp REAL,
  blockrate REAL,
  blockrate_opp REAL,
  stealrate REAL,
  stealrate_opp REAL,
  assistrate REAL,
  assistrate_opp REAL,
  threeattamptrate REAL,
  threeattamptrate_opp REAL,
  threeperc REAL,
  threeperc_opp REAL,
  twoperc REAL,
  twoperc_opp REAL,
  ftperc REAL,
  ftperc_opp REAL,
  efgperc REAL,
  efgperc_opp REAL,
  orebperc REAL,
  orebperc_opp REAL,
  toratio REAL,
  toratio_opp REAL,
  ftrate REAL,
  ftrate_opp REAL,
  points2perc REAL,
  points2perc_opp REAL,
  points3perc REAL,
  points3perc_opp REAL,
  pointsftperc REAL,
  pointsftperc_opp REAL,
  foulsdrawnrate REAL,
  foulsdrawnrate_opp REAL,
  valuerate REAL,
  valuerate_opp REAL
);
