name: Daily Data Scrape

on:
  schedule:
    - cron: '0 21 * * *'
    # Run at 10:00 PM UTC
    - cron: '0 22 * * *'
    # Run at 11:00 PM UTC
    - cron: '0 23 * * *'
    # Run at 12:00 AM (midnight) UTC
    - cron: '0 0 * * *'
    # Run at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data scrape script
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python Stretch5DataScrape.py
        
    - name: Commit and push changes (if any)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "🤖 Daily data scrape update - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
